language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

script:
    - vendor/bin/tester tests -s -p php
    - php temp/code-checker/src/code-checker.php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.5.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
